name-template: '🚀 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    -   title: '🖌 기능이 추가되었어요'
        labels:
            - '🖌️ feature'
    -   title: '🐞 버그가 수정되었어요'
        labels:
            - '🐞 bug'
    -   title: '🛠 코드를 개선했어요'
        labels:
            - '🛠️ fix'
    -   title: '🌏️ 인프라를 개선했어요'
        labels:
            - '🌏 infra'
    -   title: '📜️ 문서를 작성했어요'
        labels:
            - '📜 document'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR '
template: |
    ## 📢 이번 업데이트 변경사항입니다.
    ---
    $CHANGES
no-changes-template: '변경사항이 없어요'
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
