spring:
    application:
        name: yappu-world
    profiles:
        active: local
        group:
            local: console-logging, secret-local
            test: console-logging
            dev: console-logging
            dev-oci: console-logging
            prod: console-logging, sentry-logging
            prod-oci: console-logging, sentry-logging
