spring:
    application:
        name: yappu-world
    profiles:
        active: local
        group:
          local: console-logging
          dev: console-logging, file-logging
          prod: file-logging
