spring:
    mvc:
        hidden-method:
            filter:
                enabled: true

    docker:
        compose:
            enabled: false

    flyway:
        enabled: false

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:yappu;MODE=Oracle;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE
        username: sa
        password:

    sql:
        init:
            mode: always

    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: none
        show-sql: true

    h2:
        console:
            enabled: true
            path: /h2-console

logging:
    level:
        p6spy: DEBUG

jwt:
    secret_key: thisisforlocalsecretkeyonlyusinginlocalenvironmentthisisforlocalsecretkeyonlyusinginlocalenvironment
    access_token_expiration_times: 3600000 # 1hour = 1000(=1s) * 60 * 60
    refresh_token_expiration_times: 1209600000 # 2weeks = 1000(=1s) * 60 * 60 * 24 * 14

management:
    endpoints:
        web:
            exposure:
                exclude: "*"
