spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            file: docker/docker-compose-test.yaml
            enabled: true
            lifecycle-management: start-and-stop
            stop:
                command: down
                timeout: 1m
            skip:
                in-tests: false
    datasource:
        url: jdbc:mysql://mysql:3306/yappu_world
        username: yapp
        password: yapp
    sql:
        init:
            mode: always

jwt:
    secret_key: ${DEV_JWT_SECRET_KEY}
    access_token_expiration_times: ${DEV_ACCESS_TOKEN_EXPIRATION_TIMES}
    refresh_token_expiration_times: ${DEV_REFRESH_TOKEN_EXPIRATION_TIMES}

fcm:
    type: service_account
    project_id: yappu-world
    private_key_id: ${FCM_PRIVATE_KEY_ID}
    private_key: ${FCM_PRIVATE_KEY}
    client_email: ${FCM_CLIENT_EMAIL}
    client_id: ${FCM_CLIENT_ID}
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: ${FCM_X509_CERT_URL}
    universe_domain: googleapis.com

discord:
    webhook: ${DISCORD_WEBHOOK_URL_IN_DEV}
