server:
    forward-headers-strategy: framework
    port: ${DEV_PORT}

spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            enabled: false
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    sql:
        init:
            mode: always

jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration_times: ${ACCESS_TOKEN_EXPIRATION_TIMES} # 1hour = 1000(=1s) * 60 * 60
    refresh_token_expiration_times: ${REFRESH_TOKEN_EXPIRATION_TIMES} # 2weeks = 1000(=1s) * 60 * 60 * 24 * 14
