spring:
    application:
        name: yappu-world
    profiles:
        active: local
        group:
            local: console-logging, secret-local, sentry-logging
            test: console-logging
            dev: console-logging, file-logging, sentry-logging
            prod: file-logging, sentry-logging
