server:
    forward-headers-strategy: framework
    port: ${DEV_SERVER_PORT}

spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            enabled: false
    datasource:
        url: ${DEV_DB_URL}
        username: ${DEV_DB_USERNAME}
        password: ${DEV_DB_PASSWORD}
    sql:
        init:
            mode: always

jwt:
    secret_key: ${DEV_JWT_SECRET_KEY}
    access_token_expiration_times: ${DEV_ACCESS_TOKEN_EXPIRATION_TIMES}
    refresh_token_expiration_times: ${DEV_REFRESH_TOKEN_EXPIRATION_TIMES}
