server:
    forward-headers-strategy: framework

spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            enabled: false
    datasource:
        url: ${DEV_DB_URL}
        username: ${DEV_DB_USERNAME}
        password: ${DEV_DB_PASSWORD}

jwt:
    secret_key: ${DEV_JWT_SECRET_KEY}
    access_token_expiration_times: ${DEV_ACCESS_TOKEN_EXPIRATION_TIMES}
    refresh_token_expiration_times: ${DEV_REFRESH_TOKEN_EXPIRATION_TIMES}

fcm:
    type: service_account
    project_id: yappu-world
    private_key_id: ${FCM_PRIVATE_KEY_ID}
    private_key: ${FCM_PRIVATE_KEY}
    client_email: ${FCM_CLIENT_EMAIL}
    client_id: ${FCM_CLIENT_ID}
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: ${FCM_X509_CERT_URL}
    universe_domain: googleapis.com

discord:
    webhook: ${DISCORD_WEBHOOK_URL_IN_DEV}

sentry:
    dsn: ${SENTRY_DSN}
    environment: dev
    traces-sample-rate: 1.0
    logging:
        minimum-event-level: warn
        minimum-breadcrumb-level: info

management:
    endpoints:
        web:
            exposure:
                include: prometheus

logging:
    level:
        p6spy: WARN

admin:
    domain: ${DEV_ADMIN_DOMAIN}

kakao:
    map_api_host: https://dapi.kakao.com
    rest_api_key: ${KAKAO_REST_API_KEY}
