spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            file: docker/docker-compose-local.yaml
            enabled: true
            lifecycle-management: start-and-stop
            stop:
                command: down
                timeout: 1m
    datasource:
        url: jdbc:mysql://localhost:3306/yappu-world
        username: yapp
        password: yapp
    sql:
        init:
            mode: always
#
#springdoc:
#    default-produces-media-type: application/json
#    default-consumes-media-type: application/json

jwt:
    secret_key: thisisforlocalsecretkeyonlyusinginlocalenvironmentthisisforlocalsecretkeyonlyusinginlocalenvironment
    access_token_expiration_times: 3600000 # 1hour = 1000(=1s) * 60 * 60
    refresh_token_expiration_times: 1209600000 # 2weeks = 1000(=1s) * 60 * 60 * 24 * 14
