server:
    forward-headers-strategy: framework

spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    docker:
        compose:
            enabled: false
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: ${PROD_OCI_DB_URL}?TNS_ADMIN=/wallet
        username: ${PROD_OCI_DB_USERNAME}
        password: ${PROD_OCI_DB_PASSWORD}
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
            connection-timeout: 30000
            idle-timeout: 600000

jwt:
    secret_key: ${PROD_JWT_SECRET_KEY}
    access_token_expiration_times: ${PROD_ACCESS_TOKEN_EXPIRATION_TIMES}
    refresh_token_expiration_times: ${PROD_REFRESH_TOKEN_EXPIRATION_TIMES}

fcm:
    type: service_account
    project_id: yappu-world
    private_key_id: ${FCM_PRIVATE_KEY_ID}
    private_key: ${FCM_PRIVATE_KEY}
    client_email: ${FCM_CLIENT_EMAIL}
    client_id: ${FCM_CLIENT_ID}
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: ${FCM_X509_CERT_URL}
    universe_domain: googleapis.com

discord:
    webhook: ${DISCORD_WEBHOOK_URL_IN_PROD}

sentry:
    dsn: ${SENTRY_DSN}
    environment: prod
    traces-sample-rate: 1.0
    logging:
        minimum-event-level: warn
        minimum-breadcrumb-level: info

management:
    endpoints:
        web:
            exposure:
                include: prometheus

logging:
    level:
        p6spy: WARN

admin:
    domain: ${PROD_DOMAIN_ADMIN}

kakao:
    map_api_host: https://dapi.kakao.com
    rest_api_key: ${KAKAO_REST_API_KEY}