services:
    mysql:
        container_name: yappu_world_mysql
        image: mysql:8.1
        environment:
            MYSQL_DATABASE: yappu-world
            MYSQL_USER: yapp
            MYSQL_PASSWORD: yapp
            MYSQL_ROOT_PASSWORD: yapp
        ports:
            - '3306:3306'
        restart: always
