services:
    mysql:
        container_name: mysql
        image: mysql:8.1
        environment:
            MYSQL_DATABASE: yappu_world
            MYSQL_USER: yapp
            MYSQL_PASSWORD: yapp
            MYSQL_ROOT_PASSWORD: yapp
        ports:
            - '3306:3306'
        restart: always
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ../src/main/resources/prometheus-local.yaml:/etc/prometheus/prometheus.yaml
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - '3000:3000'
