services:
    app:
        image: yappu-world-prod
        container_name: yappu-world-prod
        build:
            context: .
            dockerfile: dockerfile-prod
        ports:
            - '8080:8080'
        volumes:
            - /opt/oracle/wallet:/wallet:ro
