name: yappu-world-server

services:
    oracle:
        image: gvenzl/oracle-xe:21-slim-faststart
        environment:
            ORACLE_PASSWORD: yapp1234
            APP_USER: yapp
            APP_USER_PASSWORD: yapp1234
        volumes:
            - yappu_oracle_data:/opt/oracle/oradata
        ports:
            - '1521:1521'
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "healthcheck.sh"]
            interval: 10s
            timeout: 5s
            retries: 30
            start_period: 60s

volumes:
    yappu_oracle_data:
