FROM bellsoft/liberica-openjdk-alpine:21

# 애플리케이션 디렉토리 설정
WORKDIR /app

# 빌드된 JAR 파일 복사
COPY deployment/build/libs/yappu-world.jar app.jar

# dev 프로파일로 애플리케이션 실행
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "app.jar"]
