services:
    app:
        image: yappu-world-dev
        container_name: yappu-world-dev
        build:
            context: .
            dockerfile: dockerfile-dev
        ports:
            - '8090:8080'
        environment:
            - JAVA_OPTS=-Xms128m -Xmx128m
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: 448M
