services:
    app:
        image: yappu-world-prod
        container_name: yappu-world-prod
        build:
            context: .
            dockerfile: dockerfile-prod
        ports:
            - '8080:8080'
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: 512M
