ALTER TABLE SIGN_UP_APPLICATION
ADD APPLICANT_NAME VARCHAR2(100);

CREATE TABLE SIGN_UP_APPLICATION_ACTIVITY_UNIT (
    ID RAW(16) PRIMARY KEY,
    APPLICATION_ID RAW(16) NOT NULL,
    GENERATION NUMBER      NOT NULL,
    POSITION VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
