INSERT INTO SIGN_UP_APPLICATION_ACTIVITY_UNIT (
    ID, APPLICATION_ID, GENERATION, POSITION, CREATED_AT, UPDATED_AT
)
SELECT
    SYS_GUID(),
    A.ID,
    JT.GENERATION,
    JT.POSITION,
    SYSTIMESTAMP,
    SYSTIMESTAMP
FROM SIGN_UP_APPLICATION A,
    JSON_TABLE(
        A.DETAILS,
        '$.activityUnits[*]'
        COLUMNS (
            GENERATION NUMBER PATH '$.generation',
            POSITION VARCHAR2(100) PATH '$.position'
        )
    ) JT
WHERE NOT EXISTS (
    SELECT 1
    FROM SIGN_UP_APPLICATION_ACTIVITY_UNIT S
    WHERE S.APPLICATION_ID = A.ID
      AND S.GENERATION = JT.GENERATION
      AND S.POSITION = JT.POSITION
);

UPDATE SIGN_UP_APPLICATION
SET APPLICANT_NAME = JSON_VALUE(DETAILS, '$.name')
WHERE DETAILS IS NOT NULL
  AND APPLICANT_NAME IS NULL;
