CREATE TABLE TEAM_SERVICE_IMAGES (
    ID RAW(16) PRIMARY KEY,
    TEAM_SERVICE_ID RAW(16) NOT NULL,
    IMAGE_URL VARCHAR2(3000) NOT NULL,
    IS_THUMBNAIL NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_THUMBNAIL IN (0, 1)),
    DISPLAY_ORDER NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_TEAM_SERVICE_IMAGES_TEAM_SERVICE
        FOREIGN KEY (TEAM_SERVICE_ID) REFERENCES TEAM_SERVICES(ID) ON DELETE CASCADE
);
