name: yappu-world-dev-ci

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'liberica'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Copy Secrets
                uses: microsoft/variable-substitution@v1
                with:
                    files:
                        ./src/main/resources/application-test.yaml
                env:
                    jwt.secret_key: ${{ secrets.DEV_JWT_SECRET_KEY }}
                    jwt.access_token_expiration_times: ${{ secrets.DEV_ACCESS_TOKEN_EXPIRATION_TIMES }}
                    jwt.refresh_token_expiration_times: ${{ secrets.DEV_REFRESH_TOKEN_EXPIRATION_TIMES }}
                    fcm.private_key_id: ${{secrets.FCM_PRIVATE_KEY_ID}}
                    fcm.private_key: ${{secrets.FCM_PRIVATE_KEY}}
                    fcm.client_email: ${{secrets.FCM_CLIENT_EMAIL}}
                    fcm.client_id: ${{secrets.FCM_CLIENT_ID}}
                    fcm.client_x509_cert_url: ${{secrets.FCM_X509_CERT_URL}}
                    discord.webhook: ${{secrets.DISCORD_WEBHOOK_URL_IN_DEV}}

            -   name: Build with Gradle Wrapper
                run: ./gradlew clean build -Dspring.profiles.active=test

            -   name: Debug application-test.yaml
                if: always()
                run: |
                    cat ./src/main/resources/application-test.yaml
                    echo "DISCORD_WEBHOOK_URL_IN_DEV=${DISCORD_WEBHOOK_URL_IN_DEV}"
                    echo "FCM_X509_CERT_URL=${DISCORD_WEBHOOK_URL_IN_DEV}"

            # Discord Notification
#            -   name: CI Success Notification
#                uses: sarisia/actions-status-discord@v1
#                if: success()
#                with:
#                    title: ✅ 개발 환경 CI 성공 ✅
#                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#                    color: 0x00FF00
#                    username: 페페훅
#
#            -   name: CI Failure Notification
#                uses: sarisia/actions-status-discord@v1
#                if: failure()
#                with:
#                    title: ❗️개발 환경 CI 실패 ❗️
#                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#                    color: 0xFF0000
#                    username: 페페훅
