name: yappu-world-prod-cd

on:
    push:
        branches:
            - prod

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'liberica'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Copy Secrets
                uses: microsoft/variable-substitution@v1
                with:
                    files:
                        ./src/main/resources/application-prod.yaml
                env:
                    spring.datasource.url: ${{ secrets.PROD_DB_URL }}
                    spring.datasource.username: ${{ secrets.PROD_DB_USERNAME }}
                    spring.datasource.password: ${{ secrets.PROD_DB_PASSWORD }}
                    jwt.secret_key: ${{ secrets.PROD_JWT_SECRET_KEY }}
                    jwt.access_token_expiration_times: ${{ secrets.PROD_ACCESS_TOKEN_EXPIRATION_TIMES }}
                    jwt.refresh_token_expiration_times: ${{ secrets.PROD_REFRESH_TOKEN_EXPIRATION_TIMES }}
                    fcm.private_key_id: ${{secrets.FCM_PRIVATE_KEY_ID}}
                    fcm.private_key: ${{secrets.FCM_PRIVATE_KEY}}
                    fcm.client_email: ${{secrets.FCM_CLIENT_EMAIL}}
                    fcm.client_id: ${{secrets.FCM_CLIENT_ID}}
                    fcm.client_x509_cert_url: ${{secrets.FCM_X509_CERT_URL}}
                    discord.webhook: ${{secrets.DISCORD_WEBHOOK_URL_IN_PROD}}
                    sentry.dsn: ${{secrets.SENTRY_DSN}}

            -   name: Build with Gradle Wrapper
                run: ./gradlew clean build -x test -Dspring.profiles.active=prod

            -   name: Prepare File for Deployment
                run: |
                    mkdir -p deployment/prod/build/libs
                    cp ./docker/dockerfile-prod ./docker/docker-compose-prod.yaml deployment/prod/
                    cp -r ./build/libs/yappu-world-prod.jar deployment/prod/build/libs

            # Github Action 실행 서버 IP 추출
            -   name: Get Github Actions IP
                id: ip
                uses: candidob/get-runner-ip@v1.0.0

            # AWS Credentials
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_BOT_ACCESS_KEY }}
                    aws-secret-access-key: ${{ secrets.AWS_BOT_SECRET_KEY }}
                    aws-region: ap-northeast-2

            # Security Group에 Github Action 서버를 등록
            -   name: Add Github Actions IP on Security Group
                run: |
                    aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_PROD_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

            -   name: Upload files to EC2
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.AWS_PROD_EC2_HOST }}
                    username: ec2-user
                    key: ${{ secrets.AWS_PROD_EC2_SSH_PRIVATE_KEY }}
                    source: "deployment/prod/*"
                    target: "/home/ec2-user/deployment/prod"

            -   name: Deploy using Docker Compose
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.AWS_PROD_EC2_HOST }}
                    username: ec2-user
                    key: ${{ secrets.AWS_PROD_EC2_SSH_PRIVATE_KEY }}
                    script: |
                        cd /home/ec2-user/deployment/prod
                        docker-compose -f docker-compose-prod.yaml down
                        docker system prune -f
                        docker-compose -f docker-compose-prod.yaml build --no-cache
                        docker-compose -f docker-compose-prod.yaml up -d

            -   name: Remove Github Actions IP from Security Group
                if: always()
                run: |
                    aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_PROD_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    

            # Discord Notification
            -   name: CD Success Notification
                uses: sarisia/actions-status-discord@v1
                if: success()
                with:
                    title: ✅ 상용 배포 성공 ✅
                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    color: 0x00FF00
                    username: 페페훅

            -   name: CD Failure Notification
                uses: sarisia/actions-status-discord@v1
                if: failure()
                with:
                    title: ❗️상용 배포 실패 ❗️
                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    color: 0xFF0000
                    username: 페페훅
