name: yappu-world-dev-ci

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'liberica'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Copy Secrets
                uses: microsoft/variable-substitution@v1
                with:
                    files:
                        ./src/main/resources/application-dev.yaml
                env:
                    server.port: ${{ secrets.DEV_SERVER_PORT }}
                    spring.datasource.url: ${{ secrets.DEV_DB_URL }}
                    spring.datasource.username: ${{ secrets.DEV_DB_USERNAME }}
                    spring.datasource.password: ${{ secrets.DEV_DB_PASSWORD }}
                    jwt.secret_key: ${{ secrets.DEV_JWT_SECRET_KEY }}
                    jwt.access_token_expiration_times: ${{ secrets.DEV_ACCESS_TOKEN_EXPIRATION_TIMES }}
                    jwt.refresh_token_expiration_times: ${{ secrets.DEV_REFRESH_TOKEN_EXPIRATION_TIMES }}

            -   name: Build with Gradle Wrapper
                run: ./gradlew clean build --info
                env:
                    SPRING_PROFILES_ACTIVE: dev

            -   name: Backend CI Discord Notification
                uses: sarisia/actions-status-discord@v1
                if: success()
                with:
                    title: ✅ 개발 환경 CI 성공 ✅
                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    color: 00FF00
                    username: 페페훅

            -   name: Backend CI Discord Notification
                uses: sarisia/actions-status-discord@v1
                if: failure()
                with:
                    title: ❗️개발 환경 CI 실패 ❗️
                    webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    color: FF0000
                    username: 페페훅
